image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      [[ ! -z $SIGNING_KEY  ]]
      gpg --verbose --batch --import <(echo $SIGNING_KEY|base64 -d)
      echo 'pinentry-mode loopback' >> ~/.gnupg/gpg.conf
      git config --global user.signingkey $SIGNING_KEY_ID
      git config --global user.email $SIGNING_EMAIL
      git config --global commit.gpgsign true
      mkdir -p ~/.ssh
      printf %s "$GITPOD4GITPUB_KEY" | base64 -d > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      SSHKey=$(ssh-keyscan git.pub 2> /dev/null)
      echo "$SSHKey" >> ~/.ssh/known_hosts
      eval "$(ssh-agent -s)" > /dev/null
      ssh-add -q -t 1h ~/.ssh/id_rsa
      wget https://wp.org/latest.zip
      unzip latest.zip
      ln -s byline wordpress/wp-content/plugins/byline
